server:
  port: 8088
  servlet:
    path: /
logging:
  level:
    com.targetmol:  info
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.3.15:1433;DatabaseName=tsweb
    username: tsbio
    password: ts@801
#    username: elastictest
#    password: gd#TOL131
mybatis:
  type-aliases-package: com.targetmol.products.dao #别名路径
  configuration:
    map-underscore-to-camel-case: true      #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

auth:
  Key: 1l&E1Sin5NpjlsRf